// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGqTMwerCRP3oNTxB0s3NXQxTkTwfrhTQ',
    appId: '1:117073093713:web:9dc420d142a4293ba48470',
    messagingSenderId: '117073093713',
    projectId: 'copa-e8ad2',
    authDomain: 'copa-e8ad2.firebaseapp.com',
    storageBucket: 'copa-e8ad2.appspot.com',
    measurementId: 'G-P5WSGMJWGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-DiGEWvFWZwvhMkkRRJ1oT7727MbEIP0',
    appId: '1:117073093713:android:630778a0a55652dca48470',
    messagingSenderId: '117073093713',
    projectId: 'copa-e8ad2',
    storageBucket: 'copa-e8ad2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDGRLJVDu3ble1YKaWFH2c87Ze2XqR8Rs',
    appId: '1:117073093713:ios:bbee76981de87e90a48470',
    messagingSenderId: '117073093713',
    projectId: 'copa-e8ad2',
    storageBucket: 'copa-e8ad2.appspot.com',
    iosBundleId: 'com.example.copa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDGRLJVDu3ble1YKaWFH2c87Ze2XqR8Rs',
    appId: '1:117073093713:ios:bbee76981de87e90a48470',
    messagingSenderId: '117073093713',
    projectId: 'copa-e8ad2',
    storageBucket: 'copa-e8ad2.appspot.com',
    iosBundleId: 'com.example.copa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGqTMwerCRP3oNTxB0s3NXQxTkTwfrhTQ',
    appId: '1:117073093713:web:749be0f92b60a2a4a48470',
    messagingSenderId: '117073093713',
    projectId: 'copa-e8ad2',
    authDomain: 'copa-e8ad2.firebaseapp.com',
    storageBucket: 'copa-e8ad2.appspot.com',
    measurementId: 'G-8ZF87QPPEB',
  );

}